export const LIKED_PHOTOS_KEY = 'LIKED_PHOTOS';
export const DISLIKE_PHOTOS_KEY = 'DISLIKE_PHOTOS';
export const COMMENT_PHOTOS_KEY = 'COMMENT_PHOTOS';
export const DOWNLOAD_PHOTOS_KEY = 'DOWNLOAD_PHOTOS';